### PR TITLE
fix(create-analog): add dev dependency when using yarn

### LINKED ISSUE #1045: Bug: yarn fails to install peer dependencies, causing app to fail when serving
### Please provide the environment you discovered this bug in.

Not reproducible via stackblitz. Follow the below steps using `yarn` instead. 

1. yarn create analog
2. Follow the wizard to create an Angular 17 application
3. CD into the project
4. yarn
5. yarn dev

### Which area/package is the issue in?

create-analog

### Description

When using `yarn` or `bun` an exception occurs.

### Please provide the exception or error you saw

```true
❯ yarn dev
yarn run v1.22.22
warning ../../package.json: No license field
$ ng serve
failed to load config from /Users/xxxxx/projects/analog-project/vite.config.ts
An unhandled exception occurred: Cannot find package '@ngtools/webpack' imported from /Users/xxxxx/projects/analog-project/node_modules/@analogjs/vite-plugin-angular/src/lib/host.js
See "/private/var/folders/g2/5zjtwbxn4870l3qh6mxyl_vr0000gn/T/ng-9sXu9m/angular-errors.log" for further details.
error Command failed with exit code 127.
```

### Other information

To fix this, install `@angular-devkit/build-angular` manually in your project.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by sonukapoor**
Fixes `yarn dev` script error due to missing peer dependencies installation

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [X] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?

When using `yarn` as the package manager, an exception is thrown while running `yarn dev`. This happens because `yarn` doesn't install the peer dependency.

Closes #1045 

## What is the new behavior?

Adds the missing dependency

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

File: packages/create-analog/index.js [hunk 1]
```diff
@@ -354,6 +355,10 @@ function addDevDependencies(pkg) {
   );
 }
 
+function addYarnDevDependencies(pkg) {
+  pkg.devDependencies['@angular-devkit/build-angular'] = ['^17.3.5'];
```
Comment (brandonroberts) [inline packages/create-analog/index.js:359]: This should be based on the template used also. If its angular-v16, it should add the v16 version

**Review by brandonroberts — APPROVED** [review]
