### PR TITLE
feat(vite-plugin-angular): fix .ts typechecking and add disableTypeChecking option

### LINKED ISSUE #1532: Only template typecheck errors are shown with the vite plugin
### Please provide the environment you discovered this bug in.

Minimal repro is here: https://stackblitz.com/edit/stackblitz-starters-agkw6lfr?file=src%2Fmain.ts

### Which area/package is the issue in?

vite-plugin-angular

### Description

When trying out the vite angular plugin I noticed that only template type check errors are shown:

CleanShot 2025-01-02 at 14 03 41@2x

But any errors in typescript files are not shown:

CleanShot 2025-01-02 at 14 04 16@2x

### Please provide the exception or error you saw

_No response_

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by mattlewis92**
## PR Checklist

Closes #1532

## What is the new behavior?

Fixes typechecking of .ts files (implementation [borrowed from the angular CLI](https://github.com/angular/angular-cli/blob/9b57ff0552736e6fef44c0ff7e6535f9ed832c6b/packages/angular/build/src/tools/angular/compilation/aot-compilation.ts#L246-L264)). Currently only component templates are typechecked. 

As this has the potential to impact performance, we also add a `disableTypeChecking` option to disable typechecking completely (so that folks can run `ngc --noEmit` to typecheck separately)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts [hunk 1]
```diff
@@ -888,3 +895,28 @@ export function createFileEmitter(
...
+  disableTypeChecking: boolean,
+  program: ts.BuilderProgram,
+  angularCompiler?: NgtscProgram['compiler']
+) {
+  const syntacticDiagnostics = program.getSyntacticDiagnostics(sourceFile);
+
+  if (disableTypeChecking) {
+    // Syntax errors are cheap to compute and the app will not run if there are any
+    // So always show these types of errors regardless if type checking is disabled
+    return syntacticDiagnostics;
```
Comment (mattlewis92) [inline packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts:910]: This matches the behaviour of the angular cli where disabling typechecking only disables semantic diagnostics:
https://github.com/angular/angular-cli/blob/9b57ff0552736e6fef44c0ff7e6535f9ed832c6b/packages/angular/build/src/tools/esbuild/angular/compiler-plugin.ts#L378C90-L378C98

**Review by brandonroberts — APPROVED** [review]
