### PR TITLE
fix(vite-plugin-angular): update plugin to ignore tsx files

### LINKED ISSUE #100: bug: Vite Plugin tries to compile tsx files for React Components
### Please provide the environment you discovered this bug in.

I've been using react with typescript in astro and its working ifne but, when i tried integrating Angualr with astro in the same project i'm getting errors. And Angular compiler is trying to compile react components too. 

my React components :  src/components/react/*.ts
my Angular components : src/components/angular/*.tsx
my other typescript files which handles apis and data manipulation: src/components/*.ts

How can i use both react and Angular components in astro?
How can i configure angular compiler to compile only from the select angular components directory?

### Which area/package is the issue in?

astro-angular

### Description

my dependencies:

"dependencies": {
    "@analogjs/astro-angular": "^0.1.0-beta.3",
    "@angular-devkit/build-angular": "^14.2.5",
    "@angular/animations": "^14.2.5",
    "@angular/common": "^14.2.5",
    "@angular/compiler": "^14.2.5",
    "@angular/compiler-cli": "^14.2.5",
    "@angular/core": "^14.2.5",
    "@angular/language-service": "^14.2.5",
    "@angular/platform-browser": "^14.2.5",
    "@angular/platform-browser-dynamic": "^14.2.5",
    "@angular/platform-server": "^14.2.5",
    "@astrojs/react": "^1.1.4",
    "@types/react": "^18.0.21",
    "@types/react-dom": "^18.0.6",
    "astro": "^1.4.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "rxjs": "^7.5.7",
    "tslib": "^2.4.0",
    "zone.js": "^0.11.8"
  }

my config: 

{
    "extends": "./tsconfig.json",
    "compileOnSave": false,
    "compilerOptions": {
      "baseUrl": "./",
      "outDir": "./dist/out-tsc",
      "forceConsistentCasingInFileNames": true,
      "strict": true,
      "noImplicitOverride": true,
      "noPropertyAccessFromIndexSignature": true,
      "noImplicitReturns": true,
      "noFallthroughCasesInSwitch": true,
      "sourceMap": true,
      "declaration": false,
      "downlevelIteration": true,
      "experimentalDecorators": true,
      "moduleResolution": "node",
      "importHelpers": true,
      "noEmit": false,
      "target": "es2020",
      "module": "es2020",
      "lib": ["es2020", "dom"],
      "skipLibCheck": true
    },
    "angularCompilerOptions": {
      "enableI18nLegacyMessageIdFormat": false,
      "strictInjectionParameters": true,
      "strictInputAccessModifiers": true,
      "strictTemplates": true
    },
    "files": [],
    "include": ["src/**/*.ts"]
  }

### Please provide the exception or error you saw

```true
Sourcemap for "D:/Program Files/Github/Repositories/HOA_Master_New/alchemy_static/node_modules/@analogjs/astro-angular/src/server.js" points to missing source files
 error   Unable to render WelcomeCard because it is undefined!
  Did you forget to import the component or is it possible there is a typo?
Error: Unable to render WelcomeCard because it is undefined!
Did you forget to import the component or is it possible there is a typo?
    at Module.renderComponent (/node_modules/astro/dist/runtime/server/render/component.js:68:11)
 error   Unable to render WelcomeCard because it is undefined!
  Did you forget to import the component or is it possible there is a typo?
Error: Unable to render WelcomeCard because it is undefined!
Did you forget to import the component or is it possible there is a typo?
    at Module.renderComponent (/node_modules/astro/dist/runtime/server/render/component.js:68:11)     
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Other information

image

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by himyjan**
change line 125 176 from tsx to ts, set plugin not try to compile tsx file. https://github.com/analogjs/analog/issues/100#issuecomment-1272601651

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [x] vite-angular-plugin
- [ ] astro-angular
- [ ] create-analog

## What is the current behavior?

Issue Number: #100

## What is the new behavior?
1.fix #100 only comple .ts file

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks @himyjan. Let's keep this PR focused on fixing the bug. The package.json and other updates should be in a separate PR.

File: packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts [hunk 1]
```diff
@@ -122,7 +122,7 @@ export function angular(options?: PluginOptions): Plugin[] {
         await buildAndAnalyze();
       },
       async handleHotUpdate(ctx) {
-        if (/\.[cm]?tsx?$/.test(ctx.file)) {
+        if (/\.[cm]?ts?$/.test(ctx.file)) {
```
Comment (brandonroberts) [inline packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts:125]: Remove the question mark also

```suggestion
        if (/\.[cm]?ts$/.test(ctx.file)) {
```

File: packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts [hunk 2]
```diff
@@ -173,7 +173,7 @@ export function angular(options?: PluginOptions): Plugin[] {
           return;
         }
 
-        if (/\.[cm]?tsx?$/.test(id)) {
+        if (/\.[cm]?ts?$/.test(id)) {
```
Comment (brandonroberts) [inline packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts:176]: Same as above

```suggestion
        if (/\.[cm]?ts$/.test(id)) {
```

**Review by brandonroberts — CHANGES_REQUESTED** [review]

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks @himyjan! @allcontributors add @himyjan for code
