### PR TITLE
fix(vite-plugin-angular): extract `templateUrl`s using AST

### LINKED ISSUE #797: Crash if `//templateUrl: ""` comment line exists in `@Component()` on page copmponent
### Please provide the environment you discovered this bug in.

I found a very strange bug. I was able to figure out how to reproduce it completely on my end, but could not reproduce it on StackBlitz.
I'm reporting this issue because the syntax that is causing the problem is Angular's, although I think the problem is probably related to the Vite area.
I have confirmed that it does not happen with Angular alone (even with `build-angular:browser-esbuild` build).

https://stackblitz.com/edit/github-ds5ida?file=src%2Fapp%2Fpages%2Findex.page.ts

### Which area/package is the issue in?

vite-plugin-angular

### Description

The problem is that inserting the comment `// templateUrl: ""` or `// templateUrl: ''` in the `@Component()` decorator that defines the page component causes the following error and crashes the application.
The crash will not occur if the comment is slightly different, as shown below.

### **Crash:**
image

### **No crash:**
image

This also occurred in a clean project immediately after `create-analog`.

- WSL 2
- Node 18.16.1
- I selected Angular 17

### Please provide the exception or error you saw

```true
2:59:37 PM [vite] Internal server error: Failed to resolve import "/home/mirumi/dev/my-project/src/app/pages" from "src/app/pages/index.page.ts". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/mirumi/dev/my-project/src/app/pages/index.page.ts:1:1
  1  |  import { Component } from "@angular/core";
     |  ^
  2  |  import * as i0 from "@angular/core";
  3  |  export const routeMeta = {
      at formatError (file:///home/mirumi/dev/my-project/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44062:46)
      at TransformContext.error (file:///home/mirumi/dev/my-project/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44058:19)
      at normalizeUrl (file:///home/mirumi/dev/my-project/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41844:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by rlmestre**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/analogjs/analog/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [x] vite-plugin-angular
- [ ] vite-plugin-nitro
- [ ] astro-angular
- [ ] create-analog
- [ ] router
- [ ] platform
- [ ] content
- [ ] nx-plugin
- [ ] trpc

## What is the current behavior?
Closes #797 

## What is the new behavior?
Uses AST instead of string matching/replacement to parse `templateUrl`s

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/vite-plugin-angular/src/lib/component-resolvers.ts [hunk 1]
```diff
@@ -71,6 +71,18 @@ export function hasTemplateUrl(code: string) {
...
 }
 
+export function getTemplateUrls(code: string) {
+  const project = new Project({ useInMemoryFileSystem: true });
+  const sourceFile = project.createSourceFile('cmp.ts', code);
+  return sourceFile
+    .getDescendantsOfKind(SyntaxKind.PropertyAssignment)
+    .filter((property) => property.getName() === 'templateUrl')
+    .map((property) =>
+      property.getInitializer()?.getText().replace(/['"]/g, '')
```
Comment (brandonroberts) [inline packages/vite-plugin-angular/src/lib/component-resolvers.ts:81]: Does this handle this use case for the `templateUrl` if they use `templateUrl: '[param].component.html'` ? 

https://github.com/analogjs/analog/issues/876

Comment (rlmestre) [reply packages/vite-plugin-angular/src/lib/component-resolvers.ts:81]: Yeah, this gets the property value as-is from the object. The replace is to remove the string delimiters which are part of it. 

I can add a unit test for it

Comment (rlmestre) [reply packages/vite-plugin-angular/src/lib/component-resolvers.ts:81]: If you're referring to the scenario in that issue linked, that's regarding `styleUrl`s. I only modified the templateUrl resolver here

**Review by brandonroberts — APPROVED** [review]
